# Site settings
title: Diganta Misra
email: mishradiganta91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Machine Learning Engineer, Weights & Biases.
  Deep learning and Non-linear dynamics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://digantamisra98.github.io" # the base hostname & protocol for your site
twitter_username: DigantaMisra1
github_username:  digantamisra98

highlighter: rouge

# Build settings
markdown: kramdown

exclude: [vendor]
