# Site settings
title: Diganta Misra
email: mishradiganta91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Graduate Student, Mila, Computer Science, University of Montreal.
  Machine learning and Non-linear dynamics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://digantamisra98.github.io" # the base hostname & protocol for your site
twitter_username: DigantaMisra1
github_username:  digantamisra98

highlighter: pygments

flickr:
  cache_dir:       "./_cache/flickr"
  api_key:          b2029c6d511d0853aa78f53841f67034
  shared_secret:    b625fb58cfe85bd3
  access_token:     72157649043569120-c7e2504cfdc6e0ca
  access_secret:    90af57e5738fc3d2

# Build settings
markdown: kramdown

exclude: [vendor]
