name: Latex auto build
on: [push]

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            submodules: true
        - name: Github Action for LaTeX
          uses: xu-cheng/latex-action@3.2.0
          with:
              working_directory: data/latex
              root_file: main.tex
        - name: Upload PDF file
          uses: actions/upload-artifact@v4
          with:
            name: PDF
            path: data/latex/main.pdf