name: Latex auto build
on: [push]

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SUBMODULES_PRIVATE_KEY }}
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            submodules: false
        - name: Github Action for LaTeX
          uses: xu-cheng/latex-action@3.2.0
          with:
              working_directory: data/latex
              root_file: main.tex
        - name: Upload PDF file
          uses: actions/upload-artifact@v4
          with:
            name: PDF
            path: data/latex/main.pdf
        - name: Commit and push
          run: |
            git config --global user.name '3rdCore'
            git config --global user.email 'tom.marty@mila.quebec'
            git add data/latex/main.pdf
            git commit -m "Add generated PDF"
            git push