name: Latex auto build
on:
  push:
  repository_dispatch:
    types: [trigger-event]

jobs:
  test-all:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' || github.event.head_commit.message != 'Add generated PDF' }}
    steps:
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: |
              ${{ secrets.PRIVATE_KEY }}
              ${{ secrets.SUBMODULES_PRIVATE_KEY }}

        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            submodules: true
        - name: Update submodule
          run: |
            cd data/latex/TomResume
            git checkout main
            git pull origin main
        - name: List directory contents
          run: ls -R data/latex/TomResume
        - name: Check remote URL
          run: |
            git remote -v
            git remote set-url origin git@github.com:3rdCore/3rdCore.github.io.git
            git remote -v
        - name: Github Action for LaTeX
          uses: xu-cheng/latex-action@3.2.0
          with:
              working_directory: data/latex/TomResume
              root_file: main.tex
        - name: Upload PDF file
          uses: actions/upload-artifact@v4
          with:
            name: PDF
            path: data/latex/TomResume/main.pdf
        - name: Commit and push
          run: |
            git status
            git config --global user.name '3rdCore'
            git config --global user.email 'tom.marty@mila.quebec'
            cp data/latex/TomResume/main.pdf data/latex/main.pdf
            git add data/latex/main.pdf
            git commit -m "Add generated PDF"
            git push

